CREATE TABLE customer_status (
Status_ID VARCHAR(20),
Customer_ID VARCHAR(20) PRIMARY KEY,
Count SMALLINT,
Quarter VARCHAR(10),
Satisfaction_score SMALLINT,
Customer_Status VARCHAR(10),
Churn_Label BOOLEAN,
Churn_Value BOOLEAN,
Churn_Score SMALLINT,
CLTV INT,
Churn_Category VARCHAR(20),
Churn_Reason VARCHAR(100)
);
CREATE TABLE customer_services (
Status_ID VARCHAR(20),
Customer_ID VARCHAR(20) PRIMARY KEY,
Count SMALLINT,
Quarter VARCHAR(10),
Referral BOOLEAN,
Referral_Count SMALLINT,
Tenure SMALLINT,
Offer VARCHAR(20),
Phone_Service BOOLEAN,
Avg_Monthly_Long_Distance_Charges NUMERIC(8,2),
Multiple_Lines BOOLEAN,
Internet_Service BOOLEAN,
Internet_Type VARCHAR(20),
Avg_Monthly_GB_Download SMALLINT,
Online_Security BOOLEAN,
Online_Backup BOOLEAN,
Device_Protection_Plan BOOLEAN,
Premium_Tech_Support BOOLEAN,
Streaming_TV BOOLEAN,
Streaming_Movies BOOLEAN,
Streaming_Music BOOLEAN,
Unlimited_Data BOOLEAN,
Contract VARCHAR(20),
Paperless_Billing BOOLEAN,
Payment_Method VARCHAR(50),
Monthly_Charge NUMERIC(10,2),
Total_Charges NUMERIC (10,2),
Total_Refunds NUMERIC (10,2),
Total_Extra_Data_Charges SMALLINT,
Total_Long_Distance_Charges NUMERIC(10,2),
Total_Revenue NUMERIC(10,2)
);
CREATE TABLE customer_location (
Location_ID VARCHAR(20),
Customer_ID VARCHAR(20) PRIMARY KEY,
Count SMALLINT,
Country VARCHAR (20),
State VARCHAR (20),
City VARCHAR(50),
Zip_Code VARCHAR(10),
Lat_Long VARCHAR(100),
Latitude NUMERIC(10,6),
Longitude NUMERIC(10,6)
);
CREATE TABLE customer_demographics (
Customer_ID VARCHAR(20) PRIMARY KEY,
Count SMALLINT,
Gender VARCHAR(10),
Age SMALLINT,
Under_30 BOOLEAN,
Senior_Citizen BOOLEAN,
Married BOOLEAN,
Dependents BOOLEAN,
Dependent_Count SMALLINT
);